blog/urls.py
from django.contrib.admin import AdminSite
from django.urls import path
from .views import ArticleList, CatergoryList ,ArticleDetail
 #,api

app_name = "blog"
urlpatterns = [
    path('', ArticleList.as_view(), name="home"),
    path('page/<int:page>', ArticleList.as_view(), name="home"),
    path('article/<slug:slug>', ArticleDetail.as_view(), name="detail"),
    path('category/<slug:slug>', CatergoryList.as_view(), name="category"),
   # path('api', api, name="api"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('blog.urls'))
]
from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.html import format_html
from django.utils import timezone
from extensions.utils import jalali_converter

#My managers.
class ArticleManager(models.Manager):
    def published (self):
        return self.filter(status='p')

class CategoryManager(models.Manager):
    def active (self):
        return self.filter(status=True)

# Create your models here.
def persian_numbers_converter(mystr):
    numbers={
        "0": "۰",
        "1": "۱",
        "2": "۲",
        "3": "۳",
        "4": "۴",
        "5": "۵",
        "6": "۶",
        "7": "۷",
        "8": "۸",
        "9": "۹",
    }
    for e, p in numbers.items():
        mystr = mystr.replace(e, p)
    return mystr

class Category(models.Model):
    parent = models.ForeignKey('self', default=None ,null=True,blank=True, on_delete=models.SET_NULL, related_name= 'children',verbose_name="زیر دسته" )
    title = models.CharField(max_length=200,verbose_name = "عنوان دسته بندی")
    slug = models.SlugField(max_length=100,unique=True, verbose_name = "آدرس دسته بندی")
    status = models.BooleanField(default=True ,verbose_name="آیا نمایش داده شود؟")
    position =models.IntegerField(verbose_name="ردیف")
    
    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural="دسته بندی ها"
        ordering =['parent__id','position']
    def __str__(self):
        return self.title
    objects = CategoryManager()

class Article(models.Model):
    STATUS_CHOICES =(
        ('d', 'ٔ‌پیش نویس'),
        ('p','منتشر شده'),
    )
    title = models.CharField(max_length=200,verbose_name = "عنوان مقاله")
    slug = models.SlugField(max_length=100,unique=True, verbose_name = "آدرس مقاله")
    category = models.ManyToManyField(Category,verbose_name= "دسته بندی" , related_name="articles")
    description = models.TextField(verbose_name = "محتوا")
    thumbnail = models.ImageField(upload_to="images", verbose_name = "تصویر مقاله")
    publish = models.DateTimeField(default=timezone.now, verbose_name = "زمان انتشار")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1,choices=STATUS_CHOICES, verbose_name = "وضعیت")
    
    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural="مقالات"

    def __str__(self):
        return self.title

    def jpublish(self):
        return jalali_converter (self.publish)
    jpublish.short_description = "زمان انتشار"

    # def  category_published(self):
    #     return self.category.filter(status=True)  

    def  thumbnail_tag(self):
        return format_html("<img width=100 height=75 style='border-radius: 5px;' src='{}'>".format(self.thumbnail.url))
    thumbnail_tag.short_description= "تصویر"

    objects = ArticleManager()
    

blog/views.py
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404 , get_list_or_404
# from django.http import HttpResponse, JsonResponse
from .models import Article ,Category
# Create your views here.
#def home(request, page=1):
 #       articles_list=Article.objects.published()
#        paginator = Paginator(articles_list, 4)
#        articles = paginator.get_page(page)
#        context = {
#             "articles": articles,
 #       }
 #       return render(request,"blog/home.html" , context)
class ArticleList(ListView):
    #model = Article
    #template_name = "blog/home.html"
    #context_object_name ="articles"
    queryset = Article.objects.published()
    paginate_by = 2

#def detail(request, slug):
 #   context = {
  #      "article": get_object_or_404(Article, slug=slug, status="p"),
   #     "category": Category.objects.filter(status=True)
    #}
    #return render(request,"blog/detail.html", context)
class ArticleDetail(DetailView):
    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Article.objects.published(), slug=slug)


class CatergoryList(ListView):
    paginate_by = 2
    template_name = 'blog/category_obj.html'

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.articles.published()
           
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context

blog/templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

blog/templates/blog/article_detail.html
{% extends 'blog/base.html' %}
{% block title %} | {{object.title}}{% endblock %}
{% block main %}
                <!-- Page Header-->
        <header class="masthead" style="background-image: url('{{object.thumbnail.url}}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h3>{{object.title}}</h3>
                            <time>{{object.jpublish}}</time>
                            <span class="subheading">زیبایی سنت و صنعت</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7 text-justify">
                        {{object.description|linebreaks}}
                    </div>
                </div>
            </div>
        </article>
        {% endblock %}

blog/templates/blog/article_list.html
{% extends 'blog/list.html' %}

{% block header %}{%endblock%}

{% block previous_page_number %}
    {% url 'blog:home'  page_obj.previous_page_number %}
{% endblock %}

{% block next_page_number %}
    {% url 'blog:home'  page_obj.next_page_number %}
{% endblock %}

blog/templates/blog/base.html
{% load static %}
{%load base_tags%}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>صنایع دستی {% block title %}{% endblock %}</title>
        
        <link rel="icon" type="image/x-icon" href="{% static 'blog/css/styles.css' %}" />
        
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet" />
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
        
    </head>
    <body>
        <!-- Navigation-->
       
        </script> 
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{%url 'blog:home'%}">{%title%}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                {%category_navbar%}
            </div>
        </nav>
       

        {% block main%}

        {%endblock%}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

blog/templates/blog/category_list.html
{% extends 'blog/list.html' %}
{% block header %}
    <h3 class="alert alert-primary text-center"  >دسته بندی:{{category.title}}</h3>
{%endblock%}

{% block previous_page_number %}
    {% url 'blog:category' category.slug page_obj.previous_page_number %}
{% endblock %}

{% block next_page_number %}
    {% url 'blog:category' category.slug page_obj.next_page_number %}
{% endblock %}

blog/templates/blog/contact.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/contact-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>Contact Me</h1>
                            <span class="subheading">Have questions? I have answers.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
                        <div class="my-5">
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                            <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                                <div class="form-floating">
                                    <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />
                                    <label for="name">Name</label>
                                    <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                                </div>
                                <div class="form-floating">
                                    <input class="form-control" id="email" type="email" placeholder="Enter your email..." data-sb-validations="required,email" />
                                    <label for="email">Email address</label>
                                    <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                                    <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                                </div>
                                <div class="form-floating">
                                    <input class="form-control" id="phone" type="tel" placeholder="Enter your phone number..." data-sb-validations="required" />
                                    <label for="phone">Phone Number</label>
                                    <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                                </div>
                                <div class="form-floating">
                                    <textarea class="form-control" id="message" placeholder="Enter your message here..." style="height: 12rem" data-sb-validations="required"></textarea>
                                    <label for="message">Message</label>
                                    <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                                </div>
                                <br />
                                <!-- Submit success message-->
                                <!---->
                                <!-- This is what your users will see when the form-->
                                <!-- has successfully submitted-->
                                <div class="d-none" id="submitSuccessMessage">
                                    <div class="text-center mb-3">
                                        <div class="fw-bolder">Form submission successful!</div>
                                        To activate this form, sign up at
                                        <br />
                                        <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                    </div>
                                </div>
                                <!-- Submit error message-->
                                <!---->
                                <!-- This is what your users will see when there is-->
                                <!-- an error submitting the form-->
                                <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                                <!-- Submit Button-->
                                <button class="btn btn-primary text-uppercase disabled" id="submitButton" type="submit">Send</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

blog/templates/blog/detail_OLd.html
<article>
    <img src="{{article.thumbnail.url}}" alt="{{article.title}}" width="300" height="200">
    <h1>{{article.title}}</h1>
    <small>{{article.publish}}</small>
    <p>{{article.description}}</p>
</article>

blog/templates/blog/home_OLD.html
<!-- <p>{{username}}</p>
<p>{{age}}</p>
<p>{{job}}</p> -->
<center>
    {% for article in articles %} 
        <article>
            <img src="{{article.thumbnail.url}}" alt="{{article.title}}" width="300" height="200">
            <h1><a href="{% url 'blog:detail' article.slug %}">{{article.title}}</a></h1>
            <small>{{article.publish}}</small>
            <p>{{article.description}}</p>
        </article>
    {% endfor %}
</center>

blog/templates/blog/list.html
{% extends 'blog/base.html' %}
{% load static %}
{% block main %}


        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static "/blog/assets/img/home-bg.jpg" %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1 class="head-title">صنایع دستی میرزا</h1>
                            <span class="subheading">تهیه شده توسط جنگو میرزا</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            {% block header %}{% endblock %}
            {% for article in object_list %}
                            <!-- Post preview-->
            <div class="post-preview">
                <a href="{% url 'blog:detail' article.slug %}">
                    <p class="post-title">{{article.title}}</p>
                    <p class="post-subtitle">{{article.description|truncatewords:30}}</p>
                </a>
                <p class="post-meta">
                    نوشته شده توسط
                    <a href="#!">جنگو میرزا</a>
                    {{article.jpublish}}
                </p>
                <div>
                    {% for cat in article.category.active %}
                        <a href="{%url 'blog:category' cat.slug %}">#{{cat.title}}</a>
                    {%endfor%}
                </div>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            {%endfor%}
            <!-- Pager-->
            {% if is_paginated %}
                    <div class="d-flex justify-content-end mb-4">
                        {% if page_obj.has_previous %}
                        <a class="btn btn-primary text-uppercase ml-3" href="{% block previous_page_number %}{% endblock %}">&rarr;مقالات قبلی </a>
                        {% endif %}
                        {% if page_obj.has_next %}
                         <a class="btn btn-primary text-uppercase " href="{% block next_page_number %}{% endblock %}">مقالات بعدی &larr; </a>
                        {% endif %}
                    </div>
                {% endif %}
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/partials/category_loop.html
<ul class='sub-menus'>
    {% for cat in cat.children.active %}
         <li >
             <a  href="{%url 'blog:category' cat.slug %}"> {{cat.title}}</a>
                {% if cat.children.active %}
                    {% include 'blog/partials/category_loop.html' %}   
                {% endif %}
         </li> 
    {% endfor %}
 </ul>

blog/templates/blog/partials/category_navbar.html
<div id="menu" >
    <ul >
        
        <li ><a  href="{%url 'blog:home'%}">خانه</a></li>
        {% for cat in category %}
            {% if cat.parent == None %}
        <li >
            <a class='dropdown-arrow'  href="{%url 'blog:category' cat.slug %}"> {{cat.title}}</a>
            {% if cat.children.active %}
                {% include 'blog/partials/category_loop.html' %}   
            {% endif %}
        </li>
            {% endif %}
        {%endfor%}
        
    </ul>
</div>


    